# class InvalidEmbeddingGeneratorConfig(ValidationError):
#     def __repr__(self) -> str:
#         return "Invalid_Embedding_Generator_Configuration"
#
#     def __init__(self, embedding_name, wrong_model=None):
#         self.embedding_name = embedding_name
#         self.wrong_model = wrong_model
#
#     def error_message(self) -> str:
#         msg = f"Embeddings cannot be autogenerated for {self.embedding_name}. "
#         if self.wrong_model:
#             msg += (
#                 f"The model name '{self.wrong_model}' is not supported. Get a list of supported "
#                 "models by running the function `list_supported_pretrained_models()` imported
#                 from "
#                 "`arize.pandas.embeddings`"
#             )
#         return msg
#
#
# class MissingEmbeddingFeaturesForEmbeddingGenerators(ValidationError):
#     def __repr__(self) -> str:
#         return "Missing_Embedding_Features_For_Embedding_Generators"
#
#     def __init__(self, missing_embeddings):
#         self.missing_embeddings = missing_embeddings
#
#     def error_message(self) -> str:
#         return (
#             "The following embeddings cannot be autogenerated: "
#             f"{', '.join([emb_name for emb_name in self.missing_embeddings])}. "
#             "Missing embedding names in schema.embedding_feature_column_names (keys of
#             dictionary).
#         "
#         )
